title: Welcome to ice1039
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/ice1039/ice1039.github-io.git" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Cheeun'
  last_name: 'Lim'
  github_username:  ice1039  
  email: icyforest0919@gmail.com

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html
